### ISSUE TITLE
Add confirmation page for Redfin data

### ISSUE THREAD

**Issue by ezl** [ezl/binkley-offer#10]
Currently, after the redfin URL is selected, we just move on to the user added information like the property page.

Insert a "Confirm Property Details" page after the Redfin URL is processed that has a form with all the values from the redfin in a prepopulated form. This will allow the user to change any if they are incorrect.

**Comment by Tech-Dex** [comment]
This is requires backend changes and a little flow change to avoid multiple "requests" to redfin api. I will wait the refactoring into django.

**Comment by ezl** [comment]
Got it.

For now, I think implementation should probably be that after the backend gets the data from redfin, it pushes it back up to the frontend to populate a confirmation form.

Then the user does the other user entered stuff, as they currently are already doing.

Then,
1. confirmation form data (whether it is modified or not after the backend sends it to the client)
2. the user entered data (the same as it already is)

gets sent back to the backend for PDF creation.

Is that what you had in mind?

**Comment by Tech-Dex** [comment]
Mostly store the scrapped data and selected data ( from previous save ) alongside with the redfin url. And if the there is an entity with the specified redfin url you will get "Confirm Property Details" and after that you will be able to change them and create a new entity.

**Comment by Tech-Dex** [comment]
1. After you scrapped the site return an object with full details.
2. Let the user change them.
3. Send them back and create the pdf with other details provided by the full flow
