### ISSUE TITLE
BOTH TYPES: FE update to Fixtures Other section

### ISSUE THREAD

**Issue by gmit08** [ezl/binkley-offer#102]

**Comment by gmit08** [comment]
These fields should be stacked on mobile, not next to each other. Looks great on desktop currently

![image](https://user-images.githubusercontent.com/59035440/101112450-4f3cda80-35ab-11eb-985f-bb71d4f73286.png)

**Comment by Tech-Dex** [comment]
![image](https://user-images.githubusercontent.com/44111988/102248756-38cb4300-3f0a-11eb-8e52-f7fe491c0710.png)
