### ISSUE TITLE
Store some values for user to prepopulate form for user input values

### ISSUE THREAD

**Issue by ezl** [ezl/binkley-offer#11]
Many of the values are the same in the user entered values, so it would save the user time if they were preselected.

For example, all the checkboxes for property details, length of attorney review, length of inspection period, attorney name, agent license, etc.

Currently, I don't have the full list of what should be prepopulated, but I will get that this week.

I believe the correct logic for this should be:

1. If this particular property has been used before, then use THOSE specific details to prepopulate the chosen values
2. If this particular property has NOT been used before, then use the details from the property most RECENTLY processed by this user (use local storage for now, since we do not have authenticated users yet to store in a profile. in the future we may move this to the authenticated user's profile)
3. If neither of the conditions above are met, then form values are blank.

**Comment by Tech-Dex** [comment]
Agree with that. There will be persistent data via mysql after the django refactoring. This one requires backend changes too.

**Comment by ezl** [comment]
@Tech-Dex you said:

> 1)I guess we want users with email , username, password for the "broker and agent" part, which is individual for every user.
> 2)Details about a property from "Fixtures And Personal Property" will be always the same based on the property entity.

1) Yes, we will eventually have user auth, for which we will use django's default user auth. However, I don't want to do that yet for this ticket. For now can you just persist to local storage? For now, persist:

* all of the checkboxes (and input values, if they exist) on "Fixtures And Personal Property"
* all values on "Legal Mumbo Jumbo"
* all values on "Contact Info"

to local storage and prepopulate them if the same device is used.
