### ISSUE TITLE
Content - Attached - Improve checkboxes on "Closing Cost Credit"

### ISSUE THREAD

**Issue by ezl** [ezl/binkley-offer#110]
On this section, there are 3 checkboxes:

<img width="985" alt="image" src="https://user-images.githubusercontent.com/157627/105609742-ed118200-5d70-11eb-926f-10b27bee344c.png">

1. check if applicable
2. $
3.  %

This should use some conditional logic:
<img width="932" alt="image" src="https://user-images.githubusercontent.com/157627/105609923-154db080-5d72-11eb-854c-61632d9e8472.png">

**Comment by Tech-Dex** [comment]
Worked on this one on attached and detached too.
here is a no selection for Detached
![image](https://user-images.githubusercontent.com/44111988/105663955-1ef32780-5edc-11eb-915f-066dee43c2ce.png)
here is for $
![image](https://user-images.githubusercontent.com/44111988/105663994-3af6c900-5edc-11eb-9dc7-443fd1e3a064.png)
here is for %
![image](https://user-images.githubusercontent.com/44111988/105664110-8e691700-5edc-11eb-9ce1-9fe8b5c0d3f6.png)

The same results for attached too.
