### ISSUE TITLE
content - attached - add section for storage

### ISSUE THREAD

**Issue by ezl** [ezl/binkley-offer#111]
on the "parking and storage" page we only have questions for parking. we aren't asking the questions for the corresponding "storage" info.

<img width="993" alt="image" src="https://user-images.githubusercontent.com/157627/105609956-475f1280-5d72-11eb-9d33-22afcdb60270.png">

**Comment by Tech-Dex** [comment]
We never had these fields. Here is the attached template how it looks like and what fields we have between 5-8 rows

![image](https://user-images.githubusercontent.com/44111988/105611940-3ee1f880-5dc1-11eb-98cd-cd768accb4ef.png)

**Comment by ezl** [comment]
Can you add please?

**Comment by Tech-Dex** [comment]
Yes, but where in what page do we want to put these new fields ?

**Comment by Tech-Dex** [comment]
So find it where is the best to add them. So here is the UI
![image](https://user-images.githubusercontent.com/44111988/105664496-780f8b00-5edd-11eb-98c0-022da7a76978.png)
and here is the result 
![image](https://user-images.githubusercontent.com/44111988/105664521-89589780-5edd-11eb-95d9-620a32a22fdf.png)

**Comment by ezl** [comment]
This was perfect -- you made the right decision regarding the placement of the tickets.

Good work.
