### ISSUE TITLE
console javascript error

### ISSUE THREAD

**Issue by ezl** [ezl/binkley-offer#114]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/157627/105721815-96c84e80-5eea-11eb-8db1-180e599b5e11.png">

I'm seeing this when I load. Doesn't seem to be any problems, but what is this about?

**Comment by Tech-Dex** [comment]
This one is related to Google. When we gave user option to connect with Google Account and after that to share with us his key for email we used an library. Maybe, for now will be the best to remove it this integration.

**Comment by Tech-Dex** [comment]
Should be no more
![image](https://user-images.githubusercontent.com/44111988/105796014-8e2d5200-5f96-11eb-87df-bc1d4dab6627.png)

**Comment by ezl** [comment]
OK -- understood. Thanks for explaining the cause to me.
