### ISSUE TITLE
Update previous saved profile buttons

### ISSUE THREAD

**Issue by ezl** [ezl/binkley-offer#116]
2 things for this ticket:

1. Conditional display - only show the buttons IF a previously saved profile exists (currently we are showing the button even if there are no saved profiles.
2. Move the button to below the title

<img width="903" alt="image" src="https://user-images.githubusercontent.com/157627/105722936-ce83c600-5eeb-11eb-9c59-7ab2c82fd436.png">

<img width="755" alt="image" src="https://user-images.githubusercontent.com/157627/105723042-f115df00-5eeb-11eb-939b-622fac7b6081.png">

**Comment by Tech-Dex** [comment]
![image](https://user-images.githubusercontent.com/44111988/105795493-9d5fd000-5f95-11eb-8335-fc5e58b8b19d.png)
![image](https://user-images.githubusercontent.com/44111988/105795543-b2d4fa00-5f95-11eb-8d18-8819fabff8b3.png)

Screenshot for #115 too.
 I also changed that grey button to "primary". I thinks looks better and doesn't look like a disabled button.

**Comment by ezl** [comment]
looks good!
