### ISSUE TITLE
disallow weekends on closing date

### ISSUE THREAD

**Issue by ezl** [ezl/binkley-offer#118]
For "closing date" fields on both attached and detached types, is it possible for us to disallow weekends as choices?

<img width="469" alt="closing date" src="https://user-images.githubusercontent.com/157627/106367015-49dae280-6305-11eb-8658-6dcb34b586ac.png">

**Comment by Tech-Dex** [comment]
![image](https://user-images.githubusercontent.com/44111988/106405572-59f6dd00-643f-11eb-8ca5-6a26f406ec35.png)
