### ISSUE TITLE
Support multiple PDF templates

### ISSUE THREAD

**Issue by ezl** [ezl/binkley-offer#15]
After the property info confirmation page created in #10 insert a page that allows the user to select WHICH PDF template to use.

(We will support multiple PDF types)

For now, this page will only have the 1 option that we already have. I will add another PDF template soon.

**Comment by Tech-Dex** [comment]
@ezl this might be duplicate on #38 but the new task is more detailed?

**Comment by ezl** [comment]
agreed. closing this issue.
