### ISSUE TITLE
Fix fixtures grid

### ISSUE THREAD

**Issue by ezl** [ezl/binkley-offer#22]
Currently, I think we have

```
-row
    -col
    -col
    -col
-row
    -col
    -col
    -col
```
Therefore, if we turn the col to 1/2 width, then the first 2 fit fine in one row, but the 3rd one will cascade down, leaving white space to the right of it.

One hacky solution is to just put ALL these cols into a single row. This will force them to cascade appropriately.

So try something like:

```
--row
  --b-col(cols="6" sm="3" md="2")
  --b-col(cols="6" sm="3" md="2")
  --b-col(cols="6" sm="3" md="2")
  --b-col(cols="6" sm="3" md="2")
  --b-col(cols="6" sm="3" md="2")
  --b-col(cols="6" sm="3" md="2")
  --b-col(cols="6" sm="3" md="2")
  --b-col(cols="6" sm="3" md="2")
  --b-col(cols="6" sm="3" md="2")
  --b-col(cols="6" sm="3" md="2")
  --b-col(cols="6" sm="3" md="2")
```

of course, this is invalid, because there are only supposed to be 12 cols per row.

However, I think it MAY fix the problem that you cannot get
2,3, and 4 cols to fill a single row at full width.

to try it, just remove all the b-row directives except a single b-row that contains ALL the cols on the fixtures page.

**Comment by Tech-Dex** [comment]
With cols=6, sm=3, md=2 i didn't managed to make it work. but with cols=6 ,sm=4, md=4 looks something like this one
![image](https://user-images.githubusercontent.com/44111988/95893602-a0d99d80-0d90-11eb-94a5-c83d3bc61f8f.png)
![image](https://user-images.githubusercontent.com/44111988/95893694-afc05000-0d90-11eb-9b60-5bd7cde39daa.png)
The only problem that appears is "centred" content. In the previous version i used sth like 
- row
    -col(for spacing left)
    -col
    -col
    -col
    -col(for spacing right)

**Comment by Tech-Dex** [comment]
And i can't really use align:"center" because the checkbox will not be inline
