### ISSUE TITLE
Move details from #11 to Database

### ISSUE THREAD

**Issue by Tech-Dex** [ezl/binkley-offer#29]
Store prepopulated values only for registered and logged users from local-storage client do database
 https://github.com/ezl/binkley-offer/issues/11

**Comment by ezl** [comment]
Just to confirm, ALL users will have their informatino stored to local storage.
For authenticated users, we will ALSO sync the localstorage back to the database.

Is that what you understood @Tech-Dex ?

**Comment by Tech-Dex** [comment]
Yes, we talked about a cross-platform for logged users, so that's why we will store everything.

**Comment by ezl** [comment]
perfect.
