### ISSUE TITLE
update grid on Fixtures and Personal Property page

### ISSUE THREAD

**Issue by ezl** [ezl/binkley-offer#3]
currently, each col is using `sm-3`

That means that it's 3/12 == 25% of the screen width at only sm breakpoint (576px) and up. 
So below that, it goes down to ONE column per row.

https://monosnap.com/file/ceiulB0QpOMDKYqynyeaPqFGeOYYL9

Instead (for now) making these:
`xs-6 sm-4 md-2`

Also, I noticed the last row has 5 columns containing checkboxes in it. Instead, just keep it at 4 checkboxes and let the last one cascade to the next row

**Comment by Tech-Dex** [comment]
![image](https://user-images.githubusercontent.com/44111988/94365988-ceaabb00-00dd-11eb-8bfc-ef6c4a44a11d.png)
Are we sure we want to use sm-4 ? it looks like this and i don't thing is nice ?
Now on mobile this one looks fine.
![image](https://user-images.githubusercontent.com/44111988/94366018-eb46f300-00dd-11eb-9d20-d5642f32a504.png)
And on full screen looks fine too 
![image](https://user-images.githubusercontent.com/44111988/94366044-0fa2cf80-00de-11eb-9b42-95df52b56706.png)

@ezl

**Comment by ezl** [comment]
@Tech-Dex I see what's happening with the `sm-4` ...

My guess is that the row has 4 cols in it, so originally it was:

```
row
-> col.sm3
-> col.sm3
-> col.sm3
-> col.sm3

row 
...
```

So it cascades fine.

However switching to

```
row
-> col.sm4
-> col.sm4
-> col.sm4
-> col.sm4
row 
...
```
means that the first 3 cols in the row take the whole span, then the next one cascades down.

We *could* fix this by only putting 3 cols per row, but it's not clear to me that's going to be the right distance.

## Requested resolution:

For now, just leave the `sm` size as `sm-3` (but still specify the xs and md, so `xs-6 sm-4 md-2`)

After the labels are inline with the checkboxes and the other tickets are done, we can revisit the specific grid layout.
