### ISSUE TITLE
persist values between pages on pressing forward/back

### ISSUE THREAD

**Issue by ezl** [ezl/binkley-offer#33]
What I mean is:

If:
1. I am on page 2 (offer details) and I enter a bunch of data
2. I press Next, which takes me to page 3
3. I enter a bunch of data on page 3
4. I think "Oh I want to change something on `offer details`" so I press "back" in my browser

then page 2 fields will all be blank (whatever was typed in step 1 is no longer there)

**Comment by Tech-Dex** [comment]
Link this one to #29
