### ISSUE TITLE
LOGIN/SIGNUP: Login Page and Homepage

### ISSUE THREAD

**Issue by Tech-Dex** [ezl/binkley-offer#35]
Login page and home page>login page

See comments

**Comment by ezl** [comment]
1. create separate /login and /signup pages -- these, of course are just simple forms for logging in and signing up.

2. to access the /login and /signup pages, put these in a navbar like this: https://getbootstrap.com/docs/4.5/examples/carousel/ (login and signup links are visible, but right justified on wideviewports; on narrow viewports, everything disappears and only a hamburger is displayed. clicking hamburger drops down login and signup links). In our implementation of this, keep the background white and use dark text on it (match the style of the rest of the page)

3. if the user is logged in, then the login and signup buttons become a user icon (`person-circle` from https://bootstrap-vue.org/docs/icons/#bootstrap-icons) and the email address of the user + a Log Out link (which logs the user out)

**Comment by gmit08** [comment]
Splitting Eric's notes above into a few tickets. This one will be for login page and home page update

Home page update (see first half of this image): 
![20201103_130637](https://user-images.githubusercontent.com/59035440/98026586-5a002600-1dd9-11eb-98f2-f557cbfb9458.jpg)

Login page: ![image](https://user-images.githubusercontent.com/59035440/98026156-b31b8a00-1dd8-11eb-856a-fc9bdda38937.png)

FLOWS: Home page > Login page

**Comment by gmit08** [comment]
@mascarell when you get to this, the first half of my image for the "Home" page was supposed to be the lower half of the original hom screen (where the user selects attached or detatched). Can you work with Dex to adjust this? I don't want login as the home page and don't want it to be a hindrance to someone wanting to use the app. Instead, we have the Create an Account page/flow as outlined in #72 . Let me know if anything is unclear.

**Comment by gmit08** [comment]
Changing the user flow to old home page and being able to enter information without having to log in will make new bug #91 not critical. Please see comment and original instructions to move the pages/flows around. @mascarell 

FLOW 1 (no login):
Attached/Detatched page > select attached or detatched > complete form > Create an Account (button is already there) > Create Account page

FLOW 2 (get started button):
Attached/Detatched page > select Get Started button > Create Account page > Attached/Detatched page > complete form

FLOW 3 (login hyperlink):
Attached/Detatched page > select Login hyperlink > Login page > Attached/Detatched page > complete form

Flows for login/sign up menu-related button should be outlined in #73

**Comment by gmit08** [comment]
@Tech-Dex Please see above notes. Carlos is out with COVID so we need you to step in and try to fix this. Everything on the existing landing page w/ get started button should be on the same page as attached/detatched single selection... just below it. See above notes.

**Comment by gmit08** [comment]
Resolves issue / works for now!
