### ISSUE TITLE
there are 2 save profile options

### ISSUE THREAD

**Issue by ezl** [ezl/binkley-offer#36]
https://monosnap.com/file/4WcPRo1S3GG23bQP1EUteD2jGAVqXF

Is this redundant? Or do they have different functionality?

If redundant, just keep the one named: "Save for future use"

**Comment by Tech-Dex** [comment]
They are used for different things. The first one save the things in localstorage for auto-population and the second one save things on localstorage but this one is not autopopulated, it's used for 3 profiles ( broker, attorney, lender arrays) that are selectable from dropdown. I suppose we can remove the first one.

**Comment by ezl** [comment]
ok, please remove (or combine functionality).

Basically from a user perspective, all they care about is: "If the user checks to save, then it will be in the dropdown for populating from previously saved"

**Comment by Tech-Dex** [comment]
Ok then we will prepopulate with last version saved and he will have option to select from dropdown what he wants after that
