### ISSUE TITLE
Figure out how to scrape data from "Detached Single" type properties [4]

### ISSUE THREAD

**Issue by ezl** [ezl/binkley-offer#38]
https://www.redfin.com/IL/Chicago/1729-N-Winchester-Ave-60622/home/12698261

This will currently break if we try to scrape it. This will go to this PDF:
[Residential-Real-Estate-Purchase-and-Sale-Contractsinglefamtownhomes.pdf](https://github.com/ezl/binkley-offer/files/5411785/Residential-Real-Estate-Purchase-and-Sale-Contractsinglefamtownhomes.pdf)

Completed, these are the fields that should be completed (again, many are the same or similar and can be adapted from the other one):
[singlefamilyboxedfieldscomplete.pdf](https://github.com/ezl/binkley-offer/files/5416881/singlefamilyboxedfieldscomplete.pdf)

It will probably require us to use different form fields. We should consider building this in a way so that we can support arbitrary number of PDF <-> Form mappings

**Comment by gmit08** [comment]
@Tech-Dex Same MS desktop / chrome issue where I get stuck on the spinning load circle. I did try a brand new property this time.
