### ISSUE TITLE
Round 1 fixes: Single Family Attached

### ISSUE THREAD

**Issue by ezl** [ezl/binkley-offer#41]
fixtures and personal property:
-microwave is in there twice
-should be in same order as contract is (order is backwards or something)
-no need to type in after you check each one, just check box except you need to be able to type a number after: electronic garage remotes____ and ceiling fans ___

mortgage contingency:
-If you say "no" to mortgage contingency, then it draws a black X over whole text area, fields 35-49
-missing a check box

broker info:
-agent MLS needs to be "agent MLS#"
agent license needs to be "agent license # "(no one knows this, i don't know mine never put it in)
-brokerage mls need to be "brokerage mls#" (no one knows this either)

parking:
-parking pin: sometimes on redfin site, often its hidden in broker private remarks, or the list agent has no idea if parking is deeded or assigned so its not listed or inaccurate. 
-if you could pull the parking space number if its listed from redfin would be helpful. again, sometimes hidden or not listed. 

[round1fixes.pdf](https://github.com/ezl/binkley-offer/files/5416899/round1fixes.pdf)

**Comment by Tech-Dex** [comment]
Mortgage Contingency:
I Tested it there is no missing checkbox and I was unable to replicate the black X over whole text area.

**Comment by Tech-Dex** [comment]
About Parking -> I will need a page example to know what to except.

**Comment by Tech-Dex** [comment]
fixtures and personal property:

- [x] microwave is in there twice

- [ ] should be in same order as contract is (order is backwards or something) -> I need to be sure what is the desired order, not to work twice.

- [X] no need to type in after you check each one, just check box except you need to be able to type a number after: electronic garage remotes____ and ceiling fans ___ -> Not sure if i understood it right. I think it's related to another ticket and we want all details input hidden except the above one ?

mortgage contingency:

- [X] If you say "no" to mortgage contingency, then it draws a black X over whole text area, fields 35-49 -> Unable to duplicate it, 

- [X] missing a check box

broker info:

- [X] agent MLS needs to be "agent MLS#"

- [X] agent license needs to be "agent license # "(no one knows this, i don't know mine never put it in)

- [X] brokerage mls need to be "brokerage mls#" (no one knows this either)

parking:
-> Need details + Examples of pages

**Comment by ezl** [comment]
@Tech-Dex I understand where you got stuck on every item. The person who created this feedback isn't familiar with software development, so he doesn't understand how to explain it clearly.

I believe you've completed everything you can. For the other items that you had questions, more information is required before you can proceed. I've created separate tickets for some of the items noted by Kevin, which require more information before proceeding.

To explain, answers to your questions:

> should be in same order as contract is (order is backwards or something) -> I need to be sure what is the desired order, not to work twice.

Correct -- I see that the order you took was: take items in sequential COLUMNS from the spreadsheet - i.e. go down col 1 then col 2 then col 3 etc. And put those in rows. This is reasonable considering that we can't be sure how many items will be in a "row" on responsive screen widths. Kevin doesn't understand this so to him it just looks like it's the wrong order. I'll discuss with him and figure out what order he wants. This will be a separate ticket, #48, so we do not need to resolve it before closing this ticket.

>  no need to type in after you check each one, just check box except you need to be able to type a number after...

You are correct, this is a duplicate of #40, with more detail than #40. So, hide inputs on all fields EXCEPT
* electronic garage remotes
* ceiling fans

I have closed #40 since it's a less descriptive duplicate.

> mortgage contingency -  If you say "no" to mortgage contingency, then it draws a black X over whole text area, fields 35-49 -> Unable to duplicate it

I believe Kevin means that IF the user selects "no", he would like for that entire question have an "X" drawn over the question entirely.

(A) That is... not ideal, though possible of course. I think it's an uncommon UX pattern though, so I don't think it's a good idea or necessary.
(B) I will discuss with Kevin separately to confirm what he means, then will create a separate ticket based on his feedback.

No need to do anything on this.

> mortgage contingency - "I Tested it there is no missing checkbox"

I agree. I reviewed the original document with the fields highlighted. I believe Kevin omitted one item here (the loan fee maximum).

Overall, I think this section requires amendment anyways, so I'll work with Kevin to create a new and separate ticket to improve this section.

No action required here to complete this ticket.

> Parking

I will request this info from Kevin. Not needed to complete this ticket.

## Summary

The only item I think you may have been unclear on is the issue of hiding all conditionally visible inputs on fixtures page EXCEPT  (A) "electronic garage remotes" and (B) "ceiling fans" -- which should conditionally display the field IF checked.

After that, you may submit a PR for this ticket.

**Comment by Tech-Dex** [comment]
@ezl I think you can take a look in PR and merge them.
