### ISSUE TITLE
Update "Thank you" page

### ISSUE THREAD

**Issue by ezl** [ezl/binkley-offer#55]
Use this style:
https://www.figma.com/file/TgbiK0k18lvtXZ0c6mBQgA/Binkley?node-id=94%3A1035

(Keep the bullet point content the same as it currently is)

**Comment by gmit08** [comment]
@Tech-Dex Can you remove some of the spacing that exists here? For instance if there are 2 lines of break, I only want one. Spacing should be half as much as it currently is.
![Screenshot 2020-10-29 113211](https://user-images.githubusercontent.com/59035440/97595803-6f8cde80-19da-11eb-894d-360c1f5db65b.jpg)

**Comment by gmit08** [comment]
@Tech-Dex The button appears to be the same as before here. I just want it moved up a line. Can you coordinate with @mascarell for this quick fix?

**Comment by Tech-Dex** [comment]
Are you sure? I removed a br line already, i will rmv the second one too
