### ISSUE TITLE
ATTACHED SINGLE: Download PDF not working on Android OS

### ISSUE THREAD

**Issue by gmit08** [ezl/binkley-offer#61]
Chrome, Android v10
One UI version 2.5
Kernel vsn 4.19.81

Phone: Galaxy Note20 Ultra 5G

possible related: https://github.com/ezl/binkley-offer/projects/1#card-48461641

ALSO TESTED:
Chrome, Android v9, moto g(6), failed

**Comment by gmit08** [comment]
@Tech-Dex can you look into and add to this ticket:

1- What the issue is
2- What needs to be done to fix this
3- Sizing

**Comment by Tech-Dex** [comment]
https://imgur.com/a/wbPCZNJ I tried it on Android OS ( MIUI OS on Poco F2 Pro )

**Comment by gmit08** [comment]
@Tech-Dex screen recordings for you---
On Samsung Galaxy, failed: https://photos.app.goo.gl/4bGPF7hcTPBPwcDU8
On moto g(6), failed: https://photos.app.goo.gl/5QxNBgjo4xgFaXP48
both using Chrome

**Comment by gmit08** [comment]
confirmed DL works on Android
