### ISSUE TITLE
DETATCHED SINGLE: Update Legal Mumbo Jumbo Fields

### ISSUE THREAD

**Issue by gmit08** [ezl/binkley-offer#63]

**Comment by gmit08** [comment]
@mascarell See DETATCHED SINGLE tab for the fields specific to this property type. Please let me know of any questions.
[Specs.xlsx](https://github.com/ezl/binkley-offer/files/5483047/Specs.xlsx)

**Comment by gmit08** [comment]
@Tech-Dex can you confirm this is all done on the BE? If not this ticket can be for both FE and BE if you and @mascarell can work together. See above for specs.

**Comment by Tech-Dex** [comment]
As we spoke on stand-up, this one is done on BE and as a user with Postman knowledge you are able to create a Detached PDF.
Below is a list with fields that are new for detached:

- riders_or_addendums 
- offer_deadline 
- homeowner_yes 
- homeowner_no

**Comment by gmit08** [comment]
Same here @mascarell if you can drop a screenshot here and/or video showing it works I can verify. Otherwise feel free to deploy so I can review

**Comment by gmit08** [comment]
Need to update to only show on detached single; currently showing also on attached

**Comment by gmit08** [comment]
Offer Deadline Date and Time was supposed to be a short form text field @Tech-Dex with "Ex: 10/20/2020 5:00PM" as preview/help text. Can you please update? @mascarell is out with COVID.

**Comment by Tech-Dex** [comment]
![image](https://user-images.githubusercontent.com/44111988/99834881-88695980-2b6c-11eb-8262-0f09610afafd.png)

Not persistent data
