### ISSUE TITLE
BOTH TYPES: Checkboxes should load to PDF: Adobe Reader

### ISSUE THREAD

**Issue by gmit08** [ezl/binkley-offer#66]
![image](https://user-images.githubusercontent.com/59035440/98011489-e7397f80-1dc5-11eb-9345-7649aa111543.png)

Had selected 1 in each category of the app

**Comment by Tech-Dex** [comment]
Same as #58. This might be from a cached version of the PDF.

**Comment by gmit08** [comment]
@Tech-Dex Please prioritize this one for today actually. I tested this on Friday with the Binkleys (after I believe caching was resolved). Can you ensure that issue is merged then test this on 407 n Elizabeth unit 205 please?

**Comment by gmit08** [comment]
Video provided in Slack to confirm. Creating another ticket to make checkboxes larger / more visible

**Comment by gmit08** [comment]
When reviewing another ticket I see that this is actually still not working on MS/Chrome. In your video (please attach here and just tag me in the future instead of Slack if possible) --- was that on your Linux system?

1000 W WASHINGTON BLVD #204 CHICAGO IL 60607
![image](https://user-images.githubusercontent.com/59035440/98757633-f8245b00-239a-11eb-903c-8ad030e92023.png)

**Comment by gmit08** [comment]
@Tech-Dex @mascarell Note that checkboxes on MS/Chrome are not showing on ANY checkboxes in the PDF (not just in the fixtures section). Is expected behavior for me to see the option checked elsewhere in the PDF (for instance here)?
![image](https://user-images.githubusercontent.com/59035440/98758161-1b9bd580-239c-11eb-86e7-1471f72f04a5.png)

**Comment by Tech-Dex** [comment]
Yes, I used Linux/Chrome. But now I created a new one on Windows 10/Chrome
[Contract_Attached_12790583.pdf](https://github.com/ezl/binkley-offer/files/5525293/Contract_Attached_12790583.pdf)
And seems like it's working fine for me.

**Comment by gmit08** [comment]
Working when view PDF in Chrome but not in Adobe Acrobat
@mascarell @ezl can you test on Acrobat? I have the free version andlooking to replicate.

**Comment by ezl** [comment]
@gmit08 I tested this and opened a document on MS Windows using Adobe Reader and there are no checkboxes.

The same document opened in Preview on a Mac DOES have checkboxes.

This is a valid bug and for some reason checkboxes are showing up in SOME PDF readers but not others.

@Tech-Dex can you research why some items would NOT render on some PDF readers?

**Comment by Tech-Dex** [comment]
https://community.adobe.com/t5/acrobat-reader/pdf-fillable-form-not-displaying-field-data/td-p/11194143?page=1

**Comment by gmit08** [comment]
Still seeing this issue on MS - Adobe Reader free version @Tech-Dex

**Comment by gmit08** [comment]
After more research we should also test how the PDF looks on default PDF viewers for each of the 4 main systems: Preview (for Mac), iBooks (iOS), Google PDF Viewer (Android), MS Edge (MS desktop).

**Comment by gmit08** [comment]
Amending this ticket to be for checkboxes showing on PDF when viewed Adobe Reader. Currently known to not work on Mac or MS for Adobe Reader. Needs to be tested on iOS and Android.

**Comment by gmit08** [comment]
@Tech-Dex going to try to re-create template in foxit. Will need to QA viewing in browser to make sure nothing breaks.

**Comment by ezl** [comment]
stale. closing. checkbox issues now seem resolved.
