### ISSUE TITLE
LOGIN/SIGNUP: Create Account Page

### ISSUE THREAD

**Issue by gmit08** [ezl/binkley-offer#72]
Want to designate a user type as real estate broker for the only user we will have creating an account.

https://bootsnipp.com/snippets/k7A

"Create an Account" instead of "Registration"
Title left-aligned within module like other pages
Login button still appears in upper right
Use same button style as we have been using
Button says "Create Account" instead of "Register"

Fields (in order) **see attached Excel -- CREATE ACCOUNT tab for more details***:
NO username
Email
First name
Last name
Password
Password (Confirm)

Text: Enter your information below for faster form completion in the future.

<all remaining fields optional>
Agent MLS#
Agent License#
Brokerage
Brokerage MLS#
Brokerage License
Broker Address
Agent Phone
Agent Fax

FLOWS:
1. Tada (confirmation) page > autopopulate information (map the other way) into Create Account page
2. Login page > Create Account page

**Comment by gmit08** [comment]
[Specs.xlsx](https://github.com/ezl/binkley-offer/files/5483445/Specs.xlsx)

**Comment by gmit08** [comment]
![image](https://user-images.githubusercontent.com/59035440/98028869-ba449700-1ddc-11eb-87bf-ac192e9268d2.png)

***Only use this as reference -- see requirements above for specs

**Comment by Tech-Dex** [comment]
Minimum 4 characters.
    The alphabets must be between [a-z]
    At least one alphabet should be of Upper Case [A-Z]
    At least 1 number or digit between [0-9].
    At least 1 character from [ ! or @ or # or $ or % or ^ or & or * or ( or ) ].

**Comment by gmit08** [comment]
Requested changes / still need to be done to complete this ticket:

- Change "Agent Mls#" to "Agent MLS#"
- Change "Broker Mls#" to "Broker MLS#"
- When user logs in or creates an account from home page then uses the app, information should be auto-populated for Buyer's Broker's Information on Contact Info page when they get there.
- On user flow home page> get started> .... fills out Buyer's Broker's Information on Contact Info page > Tada page: Create Account button should be click-able and auto-populate with information from Buyer's Broker's Information

Nice to haves:

- Buyer's Broker's Information on Contact Info page is a saved profile and set as default for future use.
- Login button still appears in upper right
- On user flow home page> create account> completed > Home button > Home: make the Login button light-colored to indicate use has already logged in

**Comment by Tech-Dex** [comment]
Done except 
Buyer's Broker's Information on Contact Info page is a saved profile and set as default for future use. ( will do that too )
Login button still appears in upper right ( not sure what is all about )

**Comment by ezl** [comment]
Closing.
