### ISSUE TITLE
LOGIN/SIGNUP: Button/Menu/Icon

### ISSUE THREAD

**Issue by gmit08** [ezl/binkley-offer#73]
From Eric:
to access the /login and /signup pages, put these in a navbar like this: https://getbootstrap.com/docs/4.5/examples/carousel/ (login and signup links are visible, but right justified on wideviewports; on narrow viewports, everything disappears and only a hamburger is displayed. clicking hamburger drops down login and signup links). In our implementation of this, keep the background white and use dark text on it (match the style of the rest of the page)

if the user is logged in, then the login and signup buttons become a user icon (person-circle from https://bootstrap-vue.org/docs/icons/#bootstrap-icons) and the email address of the user + a Log Out link (which logs the user out)

**Comment by ezl** [comment]
closing. i don't care about auth stuff right now.
