### ISSUE TITLE
Do not cache and reuse PDFs for the same address [1]

### ISSUE THREAD

**Issue by ezl** [ezl/binkley-offer#75]
## Context:

Every time someone creates an offer letter, it's possible that some information may change on it.
(A) the information scraped from RedFin can change occasionally
(B) the user entered information (buyer, seller, amount, etc)

Also possible that the person creating the offer letter made a mistake.

## Problem:

I *believe* that we are caching PDFs for a specific property.

For example, if I generate an offer letter for property `824 W Armitage Ave Unit 2CD` (https://www.redfin.com/IL/Chicago/824-W-Armitage-Ave-60614/unit-2CD/home/171027467) today, then I do it again tomorrow, I may want totally different data.

Additionally, it's possible for multiple buyers to generate offer letters at different prices with different conditions for the same property.

Therefore, if we are currently using the PREVIOUSLY generated PDF for the same property, it will be incorrect.

## Solution:

(A) we DO still want to upload offer PDFs to S3 (currently doing this, I believe)

(B) we do NOT want to ever re-use a previous PDF if a user goes through the PDF generation process (requires change)

(C) once we have user accounts, we can save previous offer letters so they are ONLY accessible within that user's account. So we'll create a separate screen for "previously created offer letters" (no action required at this time, just explaining so you'll understand the use case for continuing to upload PDFs to S3, even though we are not using it at this time)

**Comment by Tech-Dex** [comment]
Yes, This is what I tried to explain on Slack... we kinda have 2 functionalities on a single item but we kept it like that due user account

**Comment by gmit08** [comment]
@Tech-Dex let's test on 1000 w washington and 824 w armitage
