### ISSUE TITLE
ATTACHED SINGLE: "closing cost credit" typed "10,000", it showed up as 10,"00 (double checked)

### ISSUE THREAD

**Issue by gmit08** [ezl/binkley-offer#77]
Mac/Safari

I think the comma is breaking something; I don't get this issue without the comma.

**Comment by Tech-Dex** [comment]
Will check this one, yes it might be related  to comma.

**Comment by gmit08** [comment]
From Slack from Dex to @mascarell : can you check local storage for that field? Or with Vue Ext ension

**Comment by gmit08** [comment]
@ezl this one needs testing

**Comment by ezl** [comment]
Tested. Unable to reproduce. Closing ticket as no longer valid.

I believe this may have been an issue of caching PDFs showing what someone else had previously entered rather than an actual formatting issue.
