### ISSUE TITLE
ALL TYPES: Fixtures>Other Equipment text field

### ISSUE THREAD

**Issue by gmit08** [ezl/binkley-offer#78]

**Comment by Tech-Dex** [comment]
Do we want to show text fields for this one? This is what this task is about ?

**Comment by gmit08** [comment]
@Tech-Dex if a user has entered text in this field ever, it looks like the text gets pushed to the PDF even if the checkbox for "Other Equipment" is NOT checked.

**Comment by gmit08** [comment]
This is still happening on MS for me -- can you share a screen recording @Tech-Dex

**Comment by Tech-Dex** [comment]
Added on slack

**Comment by gmit08** [comment]
QA approved on attached and detatched
