### ISSUE TITLE
BOTH TYPES: Make checkboxes larger / more visible so you don't have to zoom in - Safari

### ISSUE THREAD

**Issue by gmit08** [ezl/binkley-offer#87]
Should look like this (scaled) but all black

![image](https://user-images.githubusercontent.com/59035440/98738657-0d3ac300-2376-11eb-9591-21ca548ea2ae.png)

**Comment by gmit08** [comment]
Not sure if FE or BE -- @mascarell and @Tech-Dex please coordinate and prioritize in front of other in progress cards

**Comment by Tech-Dex** [comment]
![image](https://user-images.githubusercontent.com/44111988/99188358-37b8c180-2764-11eb-8824-136f5935a2f4.png)
I am not sure if we should make things bigger than this. On my video everythings was small, one reason might be Linux, but on Windows everythings seems fine.

**Comment by gmit08** [comment]
Yes @Tech-Dex Can we make the checkmark even bigger and bolder so there is no need to zoom in to view? If this is a windows screenshot I think that is still too small.

**Comment by Tech-Dex** [comment]
I can only make checkmarks bigger but they will fall of the checkbox. I received the PDF from @ezl and I don't think I am able to make changes, because it might be something official beside that I think it will be uglier if I will make all checkbox bigger. Maybe Eric can help us.

**Comment by gmit08** [comment]
![image](https://user-images.githubusercontent.com/59035440/99692834-bc535a80-2a58-11eb-9dbc-12ad5de1a721.png)
https://www.lightenpdf.com/product-tutorials/how-to-fill-pdf-form-mac.html

**Comment by gmit08** [comment]
@mascarell can you test this on Mac and drop a screenshot here please?

**Comment by Tech-Dex** [comment]
Should looks like this 
![image](https://user-images.githubusercontent.com/44111988/99843945-05033480-2b7b-11eb-9bd8-8f24c5f9fdd8.png)
instead when get processed by backend results in this  
![image](https://user-images.githubusercontent.com/44111988/99843971-13e9e700-2b7b-11eb-9b3e-3c6944fdb25d.png)

**Comment by Tech-Dex** [comment]
So I will have to test as many multiple solutions to find the ones that fits well.

**Comment by Tech-Dex** [comment]
Difference between older and newer 
![image](https://user-images.githubusercontent.com/44111988/99845299-15b4aa00-2b7d-11eb-8e62-9db2b91275a6.png)

**Comment by Tech-Dex** [comment]
Tested it on Photoshop CC 2020 
![image](https://user-images.githubusercontent.com/44111988/99846101-6d9fe080-2b7e-11eb-9bea-ce8b07c72b65.png)
Seems perfect

**Comment by gmit08** [comment]
@ezl we are exploring a workaround by instructing the user to open in Safari instead of the PDF viewer. Can you drop a Safari iOS and Safari desktop/Mac screenshot of the PDF checkmarks here so that @Tech-Dex can tell if he needs to make the checkboxes larger (so the user does not have to zoom in)?

**Comment by gmit08** [comment]
Amended this to be for Safari only (Mac- confirmed; iOS needs to be tested still)
