### ISSUE TITLE
ATTACHED SINGLE: Add new fields throughout app

### ISSUE THREAD

**Issue by gmit08** [ezl/binkley-offer#88]
See ATTACHED SINGLE excel doc attached in comments for full specs. Highlighted fields are the ones that need to be added or changed. Please consult the notes section and look at the order and let me know of any questions!

**Comment by gmit08** [comment]
[Specs v2.xlsx](https://github.com/ezl/binkley-offer/files/5526701/Specs.v2.xlsx)

**Comment by gmit08** [comment]
https://ericsprojects.slack.com/files/U01BJ91NF0A/F01E9Q6KZN3/demo_some_fields.mp4
https://ericsprojects.slack.com/files/U01BJ91NF0A/F01F39K2PK3/demo_last_fields.mp4
https://ericsprojects.slack.com/files/U01BJ91NF0A/F01EMLNLPV3/contract_attached_13352313.pdf

**Comment by gmit08** [comment]
Requested FE changes-- all for @mascarell unless otherwise specified.
On Prop Details page:
- Change "Buyer to deliver Association documents within:" to "Business Days to Deliver Documents:" and update the text in grey box from "business days" to "Days"
- Tax Exemptions question -- let's actually remove this. It should not be connecting to the PDF - please confirm @Tech-Dex 
- 4 exemptions checkboxes should be "Shown in a grid like on fixtures page, ordered left to right in the app as they are listed here so user can check the boxes. "
- Other is missing "Include example text: "105% or tbd"

Parking and Storage: All FE needs to be fixed to mirror rest of app. See excel sheet orders/specs. "Shown in a grid like on fixtures page, ordered left to right in the app as they are listed here. No title, just show below Q1"

Fixtures page - Other -- Looks great @Tech-Dex! I was pleasantly surprised. @mascarell Can you confirm this looks good on mobile (i.e., is stacked)?

Last field- leave blank for default; do not use current date as default -- may need to coordinate w/ @Tech-Dex

**Comment by gmit08** [comment]
Requested BE changes / PDF mapping @Tech-Dex :
Make all longform text fields show up as the user enters it / do not transform to all caps in the PDF please.
"Attached Riders and Addendums" should map to 112 on the PDF and overflow into 113 (perhaps split this on the BE based on how many characters will fit -- make sure it fills to the end of line 112 before overflowing to 113).
Currently "Contract accepted by seller on or before" appears to be mapped to line 112 but it should be line 114. Please ensure the date matches the US format like other date fields. Thank you!

**Comment by Tech-Dex** [comment]
1. I will check about Capitalize issue on PDF.. seems this happens to every text-field. Also there might be a problem on "Attached Riders and Addendums" bcs in PDF there are 2 different fields sth like. attached_riders_and_addendums_1 and attached_riders_and_addendums_2 and it will be a bit hard to overflow from 1 into 2 and there might appear some errors or big whitespaces if we don't want to split a word on 2 fields ( I don't know if in English is allowed to split a word in syllables or if it's fine to do that in that PDF )
2. About "Contract accepted by seller on or before" I think I fixed as I said in slack, but I will review that again.
3. > Tax Exemptions question -- let's actually remove this. It should not be connecting to the PDF - please confirm @Tech-Dex 

I am not sure which one.

**Comment by gmit08** [comment]
For riders and addendums split on space for the second line

**Comment by gmit08** [comment]
@mascarell I spoke w/ Dex. Can you change the Tax Exemptions from a checkbox to Yes/No radio dial button like for Dual Agency?

**Comment by gmit08** [comment]
@ see above tasks assigned to Carlos

**Comment by gmit08** [comment]
@Tech-Dex noticed these were also pushed to DETATCHED SINGLE which should not have been the case. Please go to detatched single and suppress:
Buyer to deliver Association documents within
Entire parking and storage page

**Comment by gmit08** [comment]
Above were removed but looks like all tax exemption questions were also removed but this is OK since Binkleys did not request it

pending FE fixes but all ATTACHED is functional and working!

**Comment by Tech-Dex** [comment]
On the excel Tax Exemption question was available only on attached flow and is present only on this one.
![image](https://user-images.githubusercontent.com/44111988/99861105-ce8ae100-2b9d-11eb-9ed6-52fb3d4b9577.png)

**Comment by gmit08** [comment]
any outstanding FE issues not required for MVP moved to #94
