### ISSUE TITLE
Login Fail Bug

### ISSUE THREAD

**Issue by gmit08** [ezl/binkley-offer#91]
Cannot use app when login is the home page; says email and PW are wrong even though it has been saved in my Google Passwords and has not been changed.

**Comment by gmit08** [comment]
![image](https://user-images.githubusercontent.com/59035440/99489947-de54bc00-2936-11eb-8efd-5f5c376bbbba.png)

**Comment by Tech-Dex** [comment]
The database was reset a few days ago. So your account might be deleted. I tried to create a new one and login with it and worked
