### ISSUE TITLE
Some unit/apt numbers not populating in app

### ISSUE THREAD

**Issue by gmit08** [ezl/binkley-offer#95]
From #60: 1832 n orleans. I noticed that Redfin address says Unit T in search but that Unit T did not make it into the Confirm Details page. Could this be related for this property (maybe the scraper needs to be adjusted?)? -- feel free to make a new issue.

Unit T still not showing up
![image](https://user-images.githubusercontent.com/59035440/100111293-f26b5280-2e3b-11eb-8195-d33ac96bd172.png)

**Comment by Tech-Dex** [comment]
We are using for Property Street Address result from this page after search 
![image](https://user-images.githubusercontent.com/44111988/100257612-ca204880-2f4e-11eb-8da9-350b42e4e4c9.png)
In Redfin Page( https://www.redfin.com/IL/Chicago/1832-N-Orleans-St-60614/unit-T/home/13345241 )  is without "Unit T" so, our scraper is not pulling this detail for this reason. Is not a bug, might be a feature but only works on some Address.

**Comment by gmit08** [comment]
Cannot be resolved since the search results we are using is Redfin's own search. However, the unit could potentially be pulled from the URL. Given this is edge case scenario but that unit number is key for attached single.

@Tech-Dex For attached single ONLY, please add the following text in bold italic red font right under Property Street Address (under the populated "823 W OAKDALE Ave Unit 2B" in this screenshot): "Please add your unit number if it is not populated above." Make it 2 font sizes smaller than "Property Street Address"
![image](https://user-images.githubusercontent.com/59035440/100640461-70c86880-3304-11eb-917e-d7e93ff1361c.png)

**Comment by gmit08** [comment]
@Tech-Dex just make sure this is only on attached

**Comment by gmit08** [comment]
@Tech-Dex I just checked attached and am not seeing it still...
![image](https://user-images.githubusercontent.com/59035440/101111463-36332a00-35a9-11eb-83cb-dbbd888a1dc6.png)

**Comment by gmit08** [comment]
@Tech-Dex Odd... I just re-opened the tab after closing it from this page and now the red text actually does appear. Do you know why this would/could have happened? Then I tested a 3rd time on incognito then the text does show up. I closed the window and went back to the prior regular Chrome window and started from the beginning then the red text was gone again. Chrome/MS desktop
![image](https://user-images.githubusercontent.com/59035440/101111610-8b6f3b80-35a9-11eb-9e19-a1f7c0664506.png)

**Comment by gmit08** [comment]
Confirmed also not showing on android/Chrome
![Screenshot_20201203-212547_Chrome](https://user-images.githubusercontent.com/59035440/101113922-6af5b000-35ae-11eb-8a38-2350b68ffce1.jpg)
