### ISSUE TITLE
BOTH TYPES: Checkboxes should load to PDF: Default PDF Viewer

### ISSUE THREAD

**Issue by gmit08** [ezl/binkley-offer#99]
From #66

Test/confirm on default PDF viewers for each of the 4 main systems: Preview (for Mac), iBooks (iOS), Google PDF Viewer (Android), MS Edge (MS desktop).

**Comment by gmit08** [comment]
@ezl can you test on Preview (for Mac), iBooks (iOS)

@Tech-Dex to test Google PDF Viewer (Android), MS Edge (MS desktop).

**Comment by Tech-Dex** [comment]
Google PDF Viewer ![image](https://user-images.githubusercontent.com/44111988/101798701-130dfa80-3b14-11eb-95aa-831c6f1ce6ff.png)

**Comment by Tech-Dex** [comment]
![image](https://user-images.githubusercontent.com/44111988/102252980-6f578c80-3f0f-11eb-920e-fc45588f706f.png)
Forgot to upload how it looks on Edge Windows. Also this one it's on 2K resolutions
